#include <iostream>
#include <time.h>
#include <cstring>

#include "src/test_cases.h"
using namespace std;

/* PROJECT 1 MAIN PROGRAM

    This file simply parses commandline input
    and calls the corresponding test_case program.

    Test case programs are stored in src/

    Do not edit this file unless its just to add another testcase for yourself

*/

int main(int argc, char **argv){

    // randomize the random number generator
    srand(time(NULL));

    // pick a test case to run, or modify to create your own
    if (argc == 1){
        cout << "error - specify test case 1, 2, or 3 at the command line" << endl;
        exit(EXIT_FAILURE);
    }

    // Test case 1 - create and manipulate a single player
    if ( strcmp(argv[1] , "1") == 0 )
        test_case_1();

    // Test case 2 - create and manipulate a team of players
    else if ( strcmp(argv[1] , "2") == 0)
        test_case_2();
    
    // Test case 3 - create two teams and trade players
    else if ( strcmp(argv[1] , "3") == 0)
        test_case_3();

    // Test case 4 - play a sample game
    else if ( strcmp(argv[1] , "4") == 0)
        test_case_4();
    
    else{
        cout << "error - invalid command line option" << endl;
        exit(EXIT_FAILURE);
    }

    return 0;
}

