"""
    Test file for the "books" class stored in books.py

    @Author: I. Obeid
    @Contact: iyad.obeid@temple.edu
    @Date: September 3, 2024

    Notes: Do not edit this file
    
    Usage:
        python lab_01.py
    
"""

import books as bk

def main():

    # test code for the "books" class
    # create three books, add them to the
    # my_books list, and then display them

    my_books = []

    # create and append book # 1
    book = bk.book()
    book.set_title("Alice in Wonderland")
    book.set_author("Lewis Carroll")
    book.set_year(1865)
    book.set_pages(112)

    my_books.append(book)

    # create and append book # 2
    book = bk.book("Fahrenheit 451","Ray Bradbury",1953,249)
    my_books.append(book)

    # create and append book # 3
    my_books.append(bk.book("Breakfast of Champions","Kurt Vonnegut",1973,303))

    # display header
    bk.display_header()

    # display includes "useless fact" which is sqrt of pages times year
    for book in my_books:
        book.display()
    print("")


main()
