/*
    Test file for the "books" class stored in books.py

    @Author: I. Obeid
    @Contact: iyad.obeid@temple.edu
    @Date: September 3, 2024

    Notes: Do not edit this file
    
    Compile:
        make lab_01
    Usage:
        ./lab_01
    
*/

#include<iostream>
#include "books.h"
using namespace std;

// main
int main(){

    books my_books[3];
    books tmpBook;

    // create and append book # 1
    tmpBook.set_title("Alice in Wonderland");
    tmpBook.set_author("Lewis Carroll");
    tmpBook.set_year(1865);
    tmpBook.set_pages(112);
    my_books[0] = tmpBook;

    // create and append book # 2
    tmpBook = books("Fahrenheit 451","Ray Bradbury",1953,249);
    my_books[1] = tmpBook;

    // create and append book # 3
    my_books[2] = books("Breakfast of Champions","Kurt Vonnegut",1973,303);

    // display header
    books::display_header();

    // display includes "useless fact" which is sqrt of pages times year
    for (int i = 0 ; i < 3 ; i++)
        my_books[i].display();
    printf("\n");


    return 0;

}